version: '3.8'

services:
  app:
    depends_on:
      - db
    build:
      context: ./
      target: dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - postgres
    ports:
      - 3000:3000
    restart: always
    env_file:
      - .env
    command: npm run start:dev
    environment:
      NODE_ENV: development

  db:
    image: postgres:11.7-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    depends_on:
      - db
    image: adminer
    networks:
      - postgres
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: hever
      ADMINER_DEFAULT_DB_DRIVER: pgsql

networks:
  postgres: {}

volumes:
  pgdata: {}